import type { CSSProperties } from 'react';

export const getOrbShadowStyle = (glowColor: string): CSSProperties => ({
  boxShadow: `0 0 45px ${glowColor}, inset 0 0 15px rgba(255, 255, 255, 0.2)`,
  transition: 'box-shadow 0.5s ease-in-out',
});

export const getAmbientGlowStyle = (glowColor: string): CSSProperties => ({
  backgroundColor: glowColor,
  transition: 'background-color 0.5s ease-in-out',
});

export const styles = {
  container: {
    padding: '16px 0',
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
    width: '100%',
    maxWidth: 480,
    margin: '0 auto',
    boxSizing: 'border-box',
  },
  card: {
    position: 'relative',
    padding: 24,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    overflow: 'hidden',
  },
  haloContainer: {
    position: 'relative',
    width: '100%',
    height: 176,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '4px 0',
  },
  haloCenter: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    pointerEvents: 'none',
  },
  haloBackdropRing: {
    position: 'absolute',
    width: 144,
    height: 144,
    borderRadius: '50%',
    background:
      'linear-gradient(to top right, color-mix(in srgb, var(--mui-palette-primary-main, #0284c7) 20%, transparent), transparent, color-mix(in srgb, var(--mui-palette-secondary-main, #006591) 20%, transparent))',
    backdropFilter: 'blur(4px)',
    border: '1px solid var(--mui-palette-divider, rgba(255, 255, 255, 0.1))',
  },
  ambientGlow: {
    position: 'absolute',
    width: 112,
    height: 112,
    borderRadius: '50%',
    filter: 'blur(24px)',
    opacity: 0.6,
  },
  orbContainer: {
    position: 'relative',
    zIndex: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 112,
    height: 112,
    borderRadius: '50%',
    backgroundColor:
      'color-mix(in srgb, var(--mui-palette-background-paper, #ffffff) 80%, transparent)',
    backdropFilter: 'blur(16px)',
    border:
      '1px solid color-mix(in srgb, var(--mui-palette-primary-main, #0284c7) 30%, transparent)',
  },
  categoryBadge: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    display: 'flex',
    justifyContent: 'center',
    pointerEvents: 'none',
  },
  categoryBadgeInner: {
    padding: '2px 10px',
    borderRadius: 9999,
    backgroundColor:
      'color-mix(in srgb, var(--mui-palette-background-paper, #ffffff) 90%, transparent)',
    border: '1px solid var(--mui-palette-divider)',
    backdropFilter: 'blur(8px)',
  },
  categoryBadgeText: {
    fontSize: '11px',
    fontWeight: 600,
    color: 'var(--mui-palette-primary-main, #0284c7)',
    letterSpacing: '0.025em',
  },
  pillsContainer: {
    width: '100%',
    marginTop: 12,
    marginBottom: 8,
  },
  pillsScrollRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    overflowX: 'auto',
    padding: '4px 2px',
    scrollbarWidth: 'none',
  },
  pillButton: {
    textTransform: 'none',
    borderRadius: 9999,
    fontSize: '11px',
    fontWeight: 500,
    padding: '4px 12px',
    minWidth: 'auto',
    flexShrink: 0,
    color: 'text.secondary',
  },
  activePillButton: {
    textTransform: 'none',
    borderRadius: 9999,
    fontSize: '11px',
    fontWeight: 600,
    padding: '4px 12px',
    minWidth: 'auto',
    flexShrink: 0,
    backgroundColor:
      'color-mix(in srgb, var(--mui-palette-primary-main, #0284c7) 15%, transparent)',
    color: 'var(--mui-palette-primary-main, #0284c7)',
    border:
      '1px solid color-mix(in srgb, var(--mui-palette-primary-main, #0284c7) 40%, transparent)',
    boxShadow:
      '0 0 12px color-mix(in srgb, var(--mui-palette-primary-main, #0284c7) 20%, transparent)',
  },
  textSection: {
    marginTop: 8,
    maxWidth: 320,
  },
  title: {
    fontWeight: 700,
    color: 'text.primary',
  },
  subtitle: {
    color: 'text.secondary',
    marginTop: 3,
    lineHeight: 1.5,
  },
  actionButtonsGroup: {
    width: '100%',
    marginTop: 24,
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  primaryCta: {
    width: '100%',
    py: 1.5,
    px: 3,
    borderRadius: 9999,
    fontWeight: 600,
    fontSize: '0.875rem',
    textTransform: 'none',
    color: 'primary.contrastText',
    backgroundColor: 'primary.main',
    boxShadow:
      '0 4px 20px color-mix(in srgb, var(--mui-palette-primary-main, #0284c7) 35%, transparent)',
    transition: 'all 0.2s ease-in-out',
    '&:hover': {
      backgroundColor: 'primary.dark',
      boxShadow:
        '0 6px 24px color-mix(in srgb, var(--mui-palette-primary-main, #0284c7) 50%, transparent)',
      transform: 'scale(1.01)',
    },
  },
  secondaryBtn: {
    width: '100%',
    py: 1,
    px: 2,
    borderRadius: 9999,
    fontWeight: 500,
    fontSize: '0.75rem',
    textTransform: 'none',
    color: 'text.primary',
    backgroundColor: 'color-mix(in srgb, var(--mui-palette-action-hover, #000000) 8%, transparent)',
    border: '1px solid var(--mui-palette-divider)',
    backdropFilter: 'blur(8px)',
    '&:hover': {
      backgroundColor:
        'color-mix(in srgb, var(--mui-palette-action-hover, #000000) 15%, transparent)',
    },
  },
  capabilitiesHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 4px',
    marginBottom: 10,
  },
  capabilitiesTitle: {
    fontSize: '11px',
    fontWeight: 600,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    color: 'text.secondary',
  },
  capabilitiesBadge: {
    fontSize: '11px',
    fontWeight: 500,
    color: 'primary.main',
    display: 'flex',
    alignItems: 'center',
    gap: 4,
  },
  capabilityCard: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    padding: 12,
    borderRadius: 12,
  },
  capabilityIconContainer: {
    width: 40,
    height: 40,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
} as const satisfies Record<string, CSSProperties | Record<string, unknown>>;
