/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as EntriesNewRouteImport } from './routes/entries/new'
import { Route as GarageIndexRouteImport } from './routes/garage/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as RemindersIndexRouteImport } from './routes/reminders/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsConflictsRouteImport } from './routes/settings/conflicts'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as GarageVehiclesNewRouteImport } from './routes/garage/vehicles/new'
import { Route as GarageVehiclesVehicleIdIndexRouteImport } from './routes/garage/vehicles/$vehicleId/index'
import { Route as GarageVehiclesVehicleIdEditRouteImport } from './routes/garage/vehicles/$vehicleId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesNewRoute = EntriesNewRouteImport.update({
  id: '/entries/new',
  path: '/entries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageIndexRoute = GarageIndexRouteImport.update({
  id: '/garage/',
  path: '/garage/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersIndexRoute = RemindersIndexRouteImport.update({
  id: '/reminders/',
  path: '/reminders/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsConflictsRoute = SettingsConflictsRouteImport.update({
  id: '/settings/conflicts',
  path: '/settings/conflicts',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageVehiclesNewRoute = GarageVehiclesNewRouteImport.update({
  id: '/garage/vehicles/new',
  path: '/garage/vehicles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageVehiclesVehicleIdIndexRoute =
  GarageVehiclesVehicleIdIndexRouteImport.update({
    id: '/garage/vehicles/$vehicleId/',
    path: '/garage/vehicles/$vehicleId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const GarageVehiclesVehicleIdEditRoute =
  GarageVehiclesVehicleIdEditRouteImport.update({
    id: '/garage/vehicles/$vehicleId/edit',
    path: '/garage/vehicles/$vehicleId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/entries/new': typeof EntriesNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/conflicts': typeof SettingsConflictsRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/garage/': typeof GarageIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/reminders/': typeof RemindersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/garage/vehicles/new': typeof GarageVehiclesNewRoute
  '/garage/vehicles/$vehicleId/edit': typeof GarageVehiclesVehicleIdEditRoute
  '/garage/vehicles/$vehicleId/': typeof GarageVehiclesVehicleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/entries/new': typeof EntriesNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/conflicts': typeof SettingsConflictsRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/garage': typeof GarageIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/reminders': typeof RemindersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/garage/vehicles/new': typeof GarageVehiclesNewRoute
  '/garage/vehicles/$vehicleId/edit': typeof GarageVehiclesVehicleIdEditRoute
  '/garage/vehicles/$vehicleId': typeof GarageVehiclesVehicleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/entries/new': typeof EntriesNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/settings/conflicts': typeof SettingsConflictsRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/garage/': typeof GarageIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/reminders/': typeof RemindersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/garage/vehicles/new': typeof GarageVehiclesNewRoute
  '/garage/vehicles/$vehicleId/edit': typeof GarageVehiclesVehicleIdEditRoute
  '/garage/vehicles/$vehicleId/': typeof GarageVehiclesVehicleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/privacy'
    | '/terms'
    | '/entries/new'
    | '/invite/$token'
    | '/settings/conflicts'
    | '/analytics/'
    | '/garage/'
    | '/onboarding/'
    | '/reminders/'
    | '/settings/'
    | '/sign-in/'
    | '/garage/vehicles/new'
    | '/garage/vehicles/$vehicleId/edit'
    | '/garage/vehicles/$vehicleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/privacy'
    | '/terms'
    | '/entries/new'
    | '/invite/$token'
    | '/settings/conflicts'
    | '/analytics'
    | '/garage'
    | '/onboarding'
    | '/reminders'
    | '/settings'
    | '/sign-in'
    | '/garage/vehicles/new'
    | '/garage/vehicles/$vehicleId/edit'
    | '/garage/vehicles/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/privacy'
    | '/terms'
    | '/entries/new'
    | '/invite/$token'
    | '/settings/conflicts'
    | '/analytics/'
    | '/garage/'
    | '/onboarding/'
    | '/reminders/'
    | '/settings/'
    | '/sign-in/'
    | '/garage/vehicles/new'
    | '/garage/vehicles/$vehicleId/edit'
    | '/garage/vehicles/$vehicleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  EntriesNewRoute: typeof EntriesNewRoute
  InviteTokenRoute: typeof InviteTokenRoute
  SettingsConflictsRoute: typeof SettingsConflictsRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  GarageIndexRoute: typeof GarageIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  RemindersIndexRoute: typeof RemindersIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
  GarageVehiclesNewRoute: typeof GarageVehiclesNewRoute
  GarageVehiclesVehicleIdEditRoute: typeof GarageVehiclesVehicleIdEditRoute
  GarageVehiclesVehicleIdIndexRoute: typeof GarageVehiclesVehicleIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/new': {
      id: '/entries/new'
      path: '/entries/new'
      fullPath: '/entries/new'
      preLoaderRoute: typeof EntriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage/': {
      id: '/garage/'
      path: '/garage'
      fullPath: '/garage/'
      preLoaderRoute: typeof GarageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/': {
      id: '/reminders/'
      path: '/reminders'
      fullPath: '/reminders/'
      preLoaderRoute: typeof RemindersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/conflicts': {
      id: '/settings/conflicts'
      path: '/settings/conflicts'
      fullPath: '/settings/conflicts'
      preLoaderRoute: typeof SettingsConflictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage/vehicles/new': {
      id: '/garage/vehicles/new'
      path: '/garage/vehicles/new'
      fullPath: '/garage/vehicles/new'
      preLoaderRoute: typeof GarageVehiclesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage/vehicles/$vehicleId/': {
      id: '/garage/vehicles/$vehicleId/'
      path: '/garage/vehicles/$vehicleId'
      fullPath: '/garage/vehicles/$vehicleId/'
      preLoaderRoute: typeof GarageVehiclesVehicleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage/vehicles/$vehicleId/edit': {
      id: '/garage/vehicles/$vehicleId/edit'
      path: '/garage/vehicles/$vehicleId/edit'
      fullPath: '/garage/vehicles/$vehicleId/edit'
      preLoaderRoute: typeof GarageVehiclesVehicleIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  EntriesNewRoute: EntriesNewRoute,
  InviteTokenRoute: InviteTokenRoute,
  SettingsConflictsRoute: SettingsConflictsRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  GarageIndexRoute: GarageIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  RemindersIndexRoute: RemindersIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  GarageVehiclesNewRoute: GarageVehiclesNewRoute,
  GarageVehiclesVehicleIdEditRoute: GarageVehiclesVehicleIdEditRoute,
  GarageVehiclesVehicleIdIndexRoute: GarageVehiclesVehicleIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
